### ISSUE TITLE
Send selected metrics from platform clusters to the centralized azure monitor

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#1000]
- [x] Azure Entra things
- [x] Changes in prometheus config: remote write
- [x] Check if metrics are working in the centralized Prom
