### ISSUE TITLE
Forbedre datakvalitet og oversikt: Gjennomgang av tagger

### ISSUE THREAD

**Issue by EivindBRisa** [Altinn/altinn-platform#1050]
# Første fase av tagging-struktur
## Beskrivelse
Vi har nå oppnådd intern enighet om hvilke tagger som skal brukes i prosjektet. Dette markerer avslutningen på den innledende diskusjonsfasen innad i teamet.

## Oppnådd

- [x] Identifisert nødvendige tagger
- [x] Oppnådd intern enighet om tagging-struktur
- [x] Dokumentert foreløpige tagg-definisjoner
- [x] Etablert struktur med taggoversikt i Confluence 

## Neste fase

Validere tagging-struktur med økonomi-teamet
Implementere den avtalte tagging-strukturen
Dokumentere endelige tagg-definisjoner

## Notater

Dette er ikke en endelig milepæl, men markerer intern konsensus
Strukturen kan fortsatt justeres basert på innspill fra andre interessenter
