### ISSUE TITLE
Implementere kostnadseffektiv og stabil dataplattform for kostnadsanalyse i Power BI

### ISSUE THREAD

**Issue by EivindBRisa** [Altinn/altinn-platform#1065]
### Description

- [x] Task 1: Evalueringsanalyse av PostgreSQL vs SQL Pool

Sammenligne kostnader og ytelse mellom PostgreSQL og SQL Pool
Teste skalerbarhet og stabilitet i PostgreSQL
Evaluere sikkerhetsfunksjoner og backup-muligheter
Diskutere beslutningsgrunnlag med anbefaling

- [x] Task 2: Implementere ETL-løsning for kostnadsdata

Sette opp Postgre SQL Server database
Konfigurere Azure Cost Management export

- [x] Task 3: Synapse vs Azure Data Factory

Flyttet stegene for datacopy pipelines fra Synapse til Azure Data Factory

- [x] Task 4: Power BI Konfigurasjon

Konfigurere direktekobling til SQL Server
Sette opp automatisk refresh (Først trenger en å identifisere det reelle behovet)

- [x] Task 5: https://github.com/Altinn/altinn-platform/issues/1060

Påbegynt utvikling av SQL script for normalisering av eksporterte data.
Analyse av data for å identifisere kandidater for normalisering.
