### ISSUE TITLE
Team Core needs help setting up workload identity for FileScan

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#1073]
### Description
We need workload identity for the [altinn-file-scan](https://github.com/Altinn/altinn-file-scan) application before we can properly remove the Shared Access Signature related code and resources. The migration project can proceed now that Storage is updated, but it would be nice if we could discontinue the support for SAS fully. It would also means deleting the SAS generating KeyVault for every application owner.

### Required accesses
File scan needs similar accesses as Storage:
- [x] `Key Vault Secrets User` access to the platform keyvault. (List, Get)
- [x] `Storage Blob Data Contributor` access to all Application Owner Storage accounts.

### Tasks
- [x] Update helm charts to enable Workload Identity and to add the client id for each AKS instance.
- [x] Create Service accounts?
- [x] Azure Entra ID configuration/role assignments for correct resources

**Comment by tjololo** [comment]
Is this a good time to remove the filescan service? We have defender with malware detection enabled for apps ref: https://github.com/Altinn/altinn-platform/issues/516

This would require some rewriting in storage I think, but that would probably be a better use of our time than fixing the filescan service?

@bengtfredh @Herskis @SandGrainOne

**Comment by SandGrainOne** [comment]
@tjololo is it more or less work than setting up EventGrid (and whatever we need, I haven't properly looked at it yet.) to get the Defender scan reports to Storage?

**Comment by tjololo** [comment]
Once files are scanned by Defender (scanned when uploaded). When malware scan is complete Defender will add two blob index tags: The scan time and the scan result. These tags should then be available on the blob once uploaded, or there is an option to send them to event grid it seems. Not sure what suites Storage best? 
https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-malware-scan#providing-scan-results

**Comment by SandGrainOne** [comment]
If we are to replicate the features provided by FileScan we would need to activaly update the DataElement with the scan result. The best way to do that would be to react to the event rather than polling for results.

**Comment by tjololo** [comment]
@bengtfredh you are more familiar than me with the setup of defender. I see there is an `eventgrid system topic` present now. Is there anything more that is need?
If the filescan always is finished the moment storage gets the OK status back from the storage account, we might just be able to update the scan status as soon as the file is uploaded, but that would require som testing and verification that the scan result always is present

**Comment by bengtfredh** [comment]
The event grid for every storageaccount is created by Azure. This is not something we have configured. I have actually been looking in to prevent this event grid to get created. I think both broker and SFVT use the event grid with some app logic, it is probably better to talk to them.

**Comment by olebhansen** [comment]
Hi, is this progressing or are you guys waiting for additional input (from us in Core)?

**Comment by tjololo** [comment]
Scheduled a meeting to find what core needs from us to replace the filescan service. Sorry for the late respons!

**Comment by tjololo** [comment]
Notes from the meeting:
* Storage needs to get notified with the blob URI and result after a scan is completed
* Core/Storage should not need to subscribe to a event grid for all service owners
* The platform (read team-platform) should provide either a POST to a http endpoint in storage or publish all events to one topic
These assumptions is to reduce the coupling between systems.
We need to get the design of this correct so my/our suggestion is to create a workload identity for filescan that can be used instead of sas-tokens while we implement the new solution.

**Comment by tjololo** [comment]
Workload identity er opprettet, holder på med utrulling i apps clustrene og gir beskjed når dette er på plass i alle miljøer.
Når det er på plass oppretter jeg en PR med nødvendige endringer i filescan charten.

Har opprettet ny isse #1589 og kopier inn notatene fra møtet som er nevnt over.

**Comment by tjololo** [comment]
PR opened for filescan helm-chart. @SandGrainOne I have set you as reviewer
