### ISSUE TITLE
Etablere OKR mål for FinOps 

### ISSUE THREAD

**Issue by EivindBRisa** [Altinn/altinn-platform#1095]
### Description

Definere og implementere OKR'er for FinOps-initiativet med fokus på dataarkitektur og rapporteringsstruktur.

- [x] Utarbeide detaljerte OKR mål
- [x] Gjennomføre gjennomgang med Børge
- [x] Avsjekk med Anne
- [x] Dokumentere endelig versjon av OKR
- [x] Dele OKR med relevante stakeholders
- [ ] #1325

**Comment by borgethommesen** [comment]
OKR lagt inn i produktstrategi for Cost Management.
https://digdir.atlassian.net/wiki/spaces/BTAP/pages/3026157613/Produktstrategi+Cost+Management 

Informasjon videreformidlet til Anne som har lagt inn i Futureworks.
