### ISSUE TITLE
Update expiring serviceprincipal used in apps cluster

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#110]
#### Issue
We have some serviceprincipal that is about to expire. This need to be updated before 22.05.2022.

#### Task
Change iac to have logic to handle this in future.

#### Tasks

- [x] Prepare aad for use of Microsoft Graph API 
- [x] Upgrade terraform provider azuread to v2.x
- [x] Add rotate_when_changed/time_rotating
- [ ] Remove permissions on Azure AD Graph API
