### ISSUE TITLE
Improve tracking of state in Apps cluster

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#136]
## Description
The job of recovering a dead Apps cluster is currently a manual job, and a tedious one with many steps. Setting up a new AKS service is relatively quick and fully automated with Terraform, but there are no automated way to redeploy the correct versions of all the apps that were hosted by the service.

The desired solution to this is GitOps. Instead of deploying apps by pushing them to the AKS service, the AKS service should pull information about all the containers it should be hosting. One such operator is flux.

[About Flux](https://fluxcd.io/docs/)
[What is GitOps](https://about.gitlab.com/topics/gitops/)
[Introduction to GitOps on Kubernetes with flux v2](https://blog.sldk.de/2021/02/introduction-to-gitops-on-kubernetes-with-flux-v2/)

## Considerations
Should the git repo be hidden from the application developers or should they have direct access to it and administrate it themselves? Automatic creation of Pull Requests? Who performs a merge?

### Ops requirements
This is primarily an ops issue, but it might have consequences for how application owners performs an app deploy.

## Specification tasks

- [ ] Development tasks are defined

## Definition of done

- [ ] Documentation (docs.altinn.studio) is updated (if relevant)
  - [ ] Technical documentation
  - [ ] User documentation
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by Herskis** [comment]
@bengtfredh @SandGrainOne 
Should we close this as not planned, as I read this I understand that it will be resolved by moving to DIS platform

**Comment by bengtfredh** [comment]
> [@bengtfredh](https://github.com/bengtfredh) [@SandGrainOne](https://github.com/SandGrainOne) Should we close this as not planned, as I read this I understand that it will be resolved by moving to DIS platform

I am thinking this are in place now - not fully adapted but design and infra are in place. It is up to product teams to convert their cd workflows.
I am thinking this is closed and finished.
