### ISSUE TITLE
Update registration of application insights in Program.cs for all components

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#185]
### Description

ApplicationInsightsLoggingBuilderExtensions.AddApplicationInsights(ILoggingBuilder, string)' is obsolete: 'InstrumentationKey based global ingestion is being deprecated. Use the AddApplicationInsights() overload which accepts Action<TelemetryConfiguration> and set TelemetryConfiguration.ConnectionString.

### Additional Information

 See https://github.com/microsoft/ApplicationInsights-dotnet/issues/2560 for more details.'

### Specification 
```cs
string applicationInsightsConnectionString = string.Empty;
applicationInsightsConnectionString = string.Format("InstrumentationKey={0}", secretBundle.Value);
```

In logging section

```cs
   // Add application insights https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger
        logging.AddApplicationInsights(
            configureTelemetryConfiguration: (config) => config.ConnectionString = applicationInsightsConnectionString,
            configureApplicationInsightsLoggerOptions: (options) => { });
```

In service registration 
```cs
       services.AddApplicationInsightsTelemetry(new ApplicationInsightsServiceOptions
        {
            ConnectionString = applicationInsightsConnectionString
        });

```
### Tasks

- [x] [Storage & receipt](https://github.com/Altinn/altinn-studio/pull/8744/files)
- [x] [Events](https://github.com/Altinn/altinn-events/pull/46)
- [x] Register
- [x]  [Profile](https://github.com/Altinn/altinn-profile/pull/15)
- [x] [Notifications](https://github.com/Altinn/altinn-notifications/pull/82)
- [x] QA
- [x] Test: verified for Register.

### Acceptance Criterias

- [x] Warning no longer appears in build
- [ ] Component still logs successfully to application insights

**Comment by acn-sbuad** [comment]
Verified all components present in application map
