### ISSUE TITLE
Move LocalTest to separate repository

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#197]
### Description

The LocalTest application should get its own repository instead of _polluting_ the altinn-studio repository. 

Name suggestion: `altinn-localtest`

### Tasks

- [ ] Create a new repository (@altinnadmin)
- [ ] Migrate code from altinn-studio to new repository. Retain all history
- [ ] Update all usage instructions in different readme files and documentation
- [ ] Delete LocalTest code from the altinn-studio repository.

### Acceptance Criterias

- [ ] Source code is moved from Altinn-studio repo.
- [ ] History is retained

**Comment by SandGrainOne** [comment]
Team platform is no longer the primary team for maintainance of LocalTest. Closing this issue and leaving it up to the studio team to decide where to host the code.
