### ISSUE TITLE
Set up Azure VPN in a way for ops to access AKS services from networks outside ai-dev

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#231]
### Description

The DevOps team member frequently work from home and needs a way to access resources in Azure. More specifically AKS services, but this is needed for a lot of services.

- AKS services
- Key Vault
- Cosmos DB
- Blob storage
- and more

### Additional Information

One idea is to enable an Azure VPN service to connect through.

### Tasks

- [x] Present PoC for security
- [x] Set up Azure VPN
- [x] Assign Azure AD access
- [ ] Network job: Routing from VPN landing zone to Azure resources.

### Acceptance Criterias

- [ ] Team members of different teams can access Azure resources without the need to go though ai-dev images.

**Comment by bengtfredh** [comment]
Doc for install and configure Azure VPN:
https://pedia.altinn.cloud/altinn-3/infrastructure/environments/network/azure-vpn/
