### ISSUE TITLE
Set up monitoring for cleanup and backup func with notifications to slack

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#252]
### Description

We removed azurerm_monitor_scheduled_query_rules_alert.function-request-failed,
we now want to reinstate it but only for the storage functions. 

### Tasks
- [x] Define alert rule
- [x] Update terraform scripts
- [x] Deploy to Test
- [x] Manual test
- [ ] Deploy to prod

### Acceptance Criterias

- [x] An alert monitoring backup and cleanup is deployed to Azure

**Comment by acn-sbuad** [comment]
Alert for at21 sent to slack when cleanup fails. 

![image.png](https://images.zenhubusercontent.com/5c8f655333fd990b927f5ea1/3d8d32d2-9b3c-4367-b24a-
cfa4ce585c6a)
