### ISSUE TITLE
Update certificate for apps clusters in prod before the expiry date 18.11.2022

### ISSUE THREAD

**Issue by alt-how** [Altinn/altinn-platform#257]
### Description

The certificate used for app clusters in prod is expiring 18.11.2022.

### Additional Information

The Certificate is used by Traefik which picks up the new certificate automatically.

### Tasks

- [x] Order new certificate @alt-how 
- [x] Add certificate to KeyVault under correct ID
- [x] Update and execute terraform pipeline

### Acceptance Criteria

New certificate is configured and working on all apps clusters for prod before the expiry.
