### ISSUE TITLE
Update certificate for platform in tt02 before the expiry date 23.11.2022

### ISSUE THREAD

**Issue by alt-how** [Altinn/altinn-platform#259]
### Description

The certificate used for platform in tt02 is expiring 23.11.2022.

### Tasks

- [x] Order new certificate @alt-how 
- [x] Add certificate to KeyVault under correct ID
- [ ] Update and execute terraform pipeline for Application Gateway.

### Acceptance Criterias

New certificate is configured and working in platform tt02 before the expiry.

**Comment by alt-how** [comment]
(Was updated 14.11)
