### ISSUE TITLE
Document action plans for Azure Monitor alerts

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#272]
### Description

The people with "vakt" duty do not have a clear action plan on what to follow up on when the alerts go off after hours. 
Each alerts should have a detailed action plan on what should be done when an alarm goes off. 
It it is deemed that the alert does not need to be acted upon immediately, consider moving it away from the critical category.	

### Specification 

- [ ] Create an overview of all alerts in TF and document who is responsible for defining an action plan

- [ ] aks-pod-in-pending-state
- [ ] aks-pod-in-faulty-state
- [ ] aks-node-in-faulty-state
- [ ] aks-average-memory-treshold
- [ ] aks-average-cpu-treshold
- [ ] testing-eformidling-{env}-platform-ai
- [ ] eformidling-integrasjonpunkt-metric-alert-{env}
- [ ] Failure Anomalies - {org}-{env}-ai
- [ ] Failure Anomalies - {env}-platform-ai
- [ ] {env}-platform-messagebox-request-unauthorized
- [ ] {org}-platform-function-threw-exception
- [ ] {org}-platform-function-request-failed
- [ ] {org}-platform-cosmosdb-ru-utilization-above-set-limit
- [ ] {org}-platform-cosmosdb-ru-expended
- [ ] {org}-platform-application-insights-http502
- [ ] {org}-inboud-event-in-poision-queue
- [ ] PostgreSQL DB shutting down
- [ ] Get Events App-Org Degraded performance

### Tasks

- [ ] Document action plans in Altinn Pedia (why, what, action plan)
- [ ] Add url to Altinn Pedia page in alert description where applicable.
- [ ] QA

### Acceptance Criterias

- [ ] An action plan exists for each of our alerts

**Comment by tjololo** [comment]
Closing this as the things have changed alot since 2022 and this will probably be handled in the EPIC #907
