### ISSUE TITLE
We get intermittent "not yet valid" errors in platform applications when validating AccessTokens

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#279]
### Description of the bug

There is an issue with clock syncronization and/or the token validity window leading to intermittent "not yet valid" errors when validating the access tokens. The two used by clients and servers needs to have a better way to handle small differences in local time between them.

0. Assuming the clocks on the app host systems is properly syncronized.
1. The first idea is to increase the window for what the validation allows. It should be possible to treat tokens as valid in a small time buffer before they actually become valid and after they've expired.
2. If the first idea fails we need to look at adding a delay so that recently generated tokens aren't used to quickly.

```
IDX10222: Lifetime validation failed. The token is not yet valid. 
ValidFrom: '10/14/2022 05:42:40', Current time: '10/14/2022 05:42:39'.
```

### Steps To Reproduce

The error is random and very hard to predict. There can be days between cases.

### Tasks

- [x] Find all errors of this kind the last month and look for the highest "time difference"
- [x] Change ClockSkew to reflect highest differene in seconds.
- [x] Publish new version of the package. 
- [x] Update the affected Platform applications with the new package.

**Comment by SandGrainOne** [comment]
There has been 55 occurrences in production the last 7 days. In all cases the time difference were less than 2 seconds. I'm still inclined to give plenty of space here and keep my suggestion of a 60 seconds ClockSkew value.

**Comment by acn-sbuad** [comment]
Successful regression test for register at22.
