### ISSUE TITLE
Update the `dihe/helseomsorg-mottak` app to send a notification when instance is created

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#288]
### Description

The [dihe/helseomsorg-mottak](https://altinn.studio/repos/dihe/helseomsorg-mottak) app should be updated to be able to send a notificaiton when a new instance is created.

### Tasks
- [x] Upgrade to v7 app nuget (https://docs.altinn.studio/community/changelog/app-nuget/v7/breaking-changes/)
- [x] Import the library created in issue #239 
- [x] Update the App logic to generate a notification when an instance is created.
- [ ] Configure the notification library and request to match the app requirements.

### Acceptance Criterias

- [ ] When a new instance of the dihe/helseomsorg-mottak is made it generates a notification to members of the organisation with access to the instance (and official organisation address).
