### ISSUE TITLE
Deploy iac for accesstokencredentials in apps

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#311]
### Description

accesstokencredentials already exists in all environments, this needs to be imported in to terraform state to prevent new accesstoken get created.

### Tasks

- [x] Create script for import accesstokencredentials in to state
- [ ] Import accesstokencredentials in to state
- [ ] Run updated iac code to verifiy

### Acceptance Criterias

All environment run iac code version with accesstokencredentials
