### ISSUE TITLE
Support for DPO shipments in eFormidling integration

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/altinn-platform#313]
### Description

Currently the eFormidling integration only supports DPF as a way of shipping data. This is limiting government organizations from using eFormidling as they need DPO.

### Additional Information

The integration code between Altinn Apps and eFormidlings integration point should be the same regardless of DPF and DPO, but it needs to be tested. In addition DPO relies on Altinn Formidling as the transport provider which requires username/password to be configured in Altinn's integration point.

The diagram below show's an example intended for SSB:

![SSB-eFormidling drawio](https://user-images.githubusercontent.com/5430430/201944709-869798a7-18ae-4286-9eac-5ef37ebcf573.svg)

Note that the arrow does not indicate flow of data, but rather who initiates the request. The data flow is from left to right.

### Analysis

Congifuration changes

```
difi.move.dpo.message-channel: altinn-integrationpoint
difi.move.feature.enableDPO=true
difi.move.dpo.username=[insert username]
difi.move.dpo.password=[insert password]
difi.move.dpo.reportees= [insert if required]
```

Username and password for DPO might have to be the same as for DigDir. This should be investigated. How to order username and password is described [here](https://samarbeid.digdir.no/eformidling/ta-i-bruk-eformidling/98)

[Information on setting up a dedicated channel for Altinn](https://docs.digdir.no/docs/eFormidling/Utvikling/kanal) 

Matching environment variables:
DIFI_MOVE_FEATURE_ENABLEDPO
DIFI_MOVE_DPO_MESSAGE_CHANNEL
DIFI_MOVE_DPO_REPORTEES
DIFI_MOVE_DPO_USERNAME
DIFI_MOVE_DPO_PASSWORD

There is no need to populate the reportees parameter. It is used in a setting not relevant to Altinn 3.

### Tasks
- [x] Get username and password for configuration
- [x] Update config values in helm charts as described [here](https://docs.digdir.no/docs/eFormidling/installasjon/Eksempel/installasjon_aks.html#7-integrasjonspunktet)
- [x] Inform [servicedesk@digdir.no](mailto:servicedesk@digdir.no) that Altinn will be using DPO
- [x] QA

### Acceptance Criterias

- [x] DPO available as a means of shipment between integration points
- [x] Internal infrastructure documentation explains the current configuration

**Comment by SandGrainOne** [comment]
Created pull request in the OPS repository. Needs review.

**Comment by acn-sbuad** [comment]
Regression test of DPF ok.
