### ISSUE TITLE
Remove tls cert secret from default namespace

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#319]
### Description

We store tls cert as a secret in default namespace. This is not needed and should be removed.

### Additional Information

In https://github.com/Altinn/altinn-studio-charts/blob/main/charts/deployment/values.yaml we have:
```yaml
  tls:
    options:
      name: tls-options
    secretName: ssl-cert
```
This should be changed to:
```yaml
  tls: null
```
By doing this traefik will use default tls cert that is defined. It is wise to keep the setting in the chart. This make it possible to add different tls cert for a ingressroute i.e. set up an ingressroute that answer to domain altinn.digdir.no

### Tasks

- [x] Update https://github.com/Altinn/altinn-studio-charts/blob/main/charts/deployment/values.yaml
- [x] Wait for all apps beeing deployed with new setting
- [x] Remove tls cert secret from default namespace all clusters

### Acceptance Criterias

- [x] tls cert secret is removed from default namespace in all clusters

**Comment by bengtfredh** [comment]
Solved as part of the ipv6 project.
