### ISSUE TITLE
Add alert for high number failures in platform

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#321]
### Description

Add alert for high number or rapid increase of failures in platform. Last deploy raised a lot of failures in platform, but was not detected until user reported issues. This should have been alerted.

## Consideration
App insights auto-generates an alert rule called `Failure anomalies`.
If we could simply add this rule to the existing action group we have that notifies Slack, our work would be done. 

### Tasks

- [x] Define a query that can be used to trigger an alert
    - [x] Separate based on role name (platform component) start with Storage.
    - [x] Filter by requests where the response is 5xx.
    - [x] time window of 5 minutes.
- [x] Define an alert rule that checks every 5 minutes.
- [x] Add necessary terraform script to apply the alert.
- [x] Have the alert published to slack (critical for prod)
- [x]  Put Terraform code here: https://dev.azure.com/brreg/_git/altinn-studio-ops?path=/provisioning/altinn_platform/scripts/terraform/aks/aks/alerts.tf

### Acceptance Criterias

- [ ] A request against Storage with a result code of 5xx generates an alert.

### Test

- Temporarily turn off auto trigger on release pipeline for Storage
- Change an endpoint in Storage to return an error. E.g GET application/org/app
- Deploy only to at21.
- Call endpoint.

**Comment by ootneim** [comment]
Er deployet til AT21 og er en del av Terraform tag 1.5.5 for platform

**Comment by acn-sbuad** [comment]
Tested by changing controller response for Application Controller, Added connection string for AT21 app insights and run storage locally. Created a console app to send request towards failing endpoint.

**Comment by acn-sbuad** [comment]
Verified in AT21.
