### ISSUE TITLE
Update platform application deploy to use latest version of kubelogin

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#326]
### Description

Current version of kubelogin "doesn't work". Use latest.

### Tasks
- [x] Kuberneteswrapper
- [x] Access Management
- [x] Authentication 
- [x] Authorization 
- [x] Events 
- [x] Notifications 
- [x] PDF 
- [x] Profile 
- [x] Receipt 
- [x] Register 
- [x] Resource Registry 
- [x] Storage 

- [x] Add new artifact to release pipelines
- [x] Add new task to [task group for deploy ](https://dev.azure.com/brreg/altinn-studio/_taskgroup/ad3e0046-307f-49a1-9e8e-e6bc1f6db050)
- [x] QA
- [x] Verification

### Additional Information

Infrastructure have already started using latest version of kubelogin from the source in their pipelines. Find out how to use it in nthe application deploy pipelines.

## Test
- [x] Regression test of release pipelines
- [x] Confirm that release pipeline now works with newer AKS versions

**Comment by SandGrainOne** [comment]
Terraform benytter denne for å laste inn kubelogin:

wget https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip
unzip kubelogin-linux-amd64.zip
sudo mv bin/linux_amd64/kubelogin /usr/bin

**Comment by ootneim** [comment]
Ser ut som det er kun kuberneteswrapper som sliter her. 
/agent/_work/_temp/azureclitaskscript1670579491372.sh: line 1: kubelogin: command not found
