### ISSUE TITLE
Analyze: Change deploy strategy for platform components

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#328]
### Description

The job of redeploying or setting up a new platform cluster with all applications is a time consuming and manual job. 
We need a way of automatically restoring an AKS cluster in a given environment. This could be in relation to restoring an environment after an incident, setting up a new cluster in a blue/green deployment or the creation of a new AT environment. 

There are multiple options here, and GitOps has been brought up as a potential solution to the problem. 

We would like to make this shift for the platform clusters where we have more stability and control before attempting to make this change for the apps clusters as well. 

### Tasks

- [x] Identify technical options to meet our challenge
- [x] Create a PoC in an AT environment 
- [x] #769
- [ ] Create issues for further work to roll out suggested solution

### Acceptance Criterias

- [ ] There exists issues for implementation and roll-out of the new deploy strategy
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/768
- [ ] https://github.com/Altinn/altinn-platform/pull/782
```
