### ISSUE TITLE
Create Altinn platform health status for external usage

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-platform#344]
## Description

It can be beneficial to expose an Altinn Platform health status to externals

## Considerations
- Web page?
- API?
- What data to include

## Specification tasks

- [ ] Development tasks are defined

## Definition of done

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by annerisbakk** [comment]
@bengtfredh kan denne lukkes og følges opp i en av Epicene nevnt over?

**Comment by bengtfredh** [comment]
@annerisbakk that is not how it works. An epic do not have any work. All work is in connected issues. This issue is connected to the epic, and need to be open to get any work.

**Comment by monteiro-renato** [comment]
Duplicated of: https://github.com/Altinn/altinn-platform/issues/918
