### ISSUE TITLE
Update the valg-valgkort app to latest versjon of the app template

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#347]
### Description

Testing of "valgkort" is soon to begin again. As preperation for that we should consider updating the app template and deployment for the app.

### Tasks

- [ ] Update the app to latest versjon of the API and Core packages
- [ ] Update the deployment chart to use recommended settings

### Acceptance Criterias

- [ ] New version of the app is available in TT02 and is able to display a "valgkort"
