### ISSUE TITLE
Adjust use case pipeline to report all failures as error

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#350]
### Description

We had a situation where tasks in the k6 script were failing and the pipeline only reporting a warning. These should be posted as errors. 

### Tasks

- [x] Find feasible solution
- [x] Update use-case.yaml pipeline
- [x] Update use-case-prod.yaml pipeline

### Acceptance Criterias
- [x] Current error in Storage in AT causes use case pipelines to fail
