### ISSUE TITLE
Prepare introduction and documentation of AI for app owners

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#354]
### Description

We frequently get requests from app owners that need an introduction on how to best use app insights. 
The information that is given to them should be standardized through documentation, videos, ect. so that it can be re-used for new application owners. 			 

What they want us to answer: How do we best utilize those opportunities that the tool provides? 

### Additional Information
- https://learn.microsoft.com/en-us/azure/azure-monitor/app/tutorial-performance
- https://learn.microsoft.com/en-us/azure/azure-monitor/app/transaction-diagnostics
- https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/

### Considerations
- Do they actually have to opportunity to do anything other than simple debugging without somewhere to persist queries or create alerts for monitoring? 

### Tasks

- [x] Identify points of interest
- [x] Identify useful documentation from Microsoft
- [x] Create a seperate section on docs for this information (e.g. operations)

### Acceptance Criterias

- [x] Documentation exists specifying how to 
  - [x] best utilize those opportunities that the tool provides? 
  - [x] basic debugging
- [x] Get feedback from SSB

**Comment by acn-sbuad** [comment]
Contacted service desk to request a new user with developer and operations access to get an impression of what the end user can access and not. Waiting for feedback.

**Comment by acn-sbuad** [comment]
Feedback from SSB: add a section on what Altinn monitors on behalf of app owners
