### ISSUE TITLE
Move Platform Models project into this repository

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#391]
### Description

The code currently located at https://github.com/Altinn/altinn-studio/tree/master/src/Altinn.Platform/Altinn.Platform.Models should be moved and reorganized here in this repo.

Folder structure:
./src/Altinn.Platform.Models/** (csproj etc)
./Altinn.Platform.Models.sln

Ensure that as much as possible of the commit history are kept for the files being moved.

### Additional Information

An tricky part of this job is to retain the commit history from the original repository for the files being transfered, but this job has been done before in for example the [AccessToken](https://github.com/Altinn/altinn-accesstoken) repository.  

### Tasks

- [x] Move source code to new repository
    - Follow instructions here:  https://ao.ms/how-to-split-a-subdirectory-to-a-new-git-repository-and-keep-the-history/
    - Move code to root
    - Work on a branch that is not main in order to create a PR with the changes. 
    - Do NOT merge the PR, once approved, rather merge directly into main to keep commit history
- [x] Restructure repository
- [x] Set up new SonarCloud project
    - [x] Create new project
    - [x] Configure project
- [x] Create GitHub actions
    ~~- [ ] CodeQL~~
    - [x] Test & analysis for internal 
    ~~- [ ] Test & analysis for fork PR~~
- [x] Check that Renovate manage to detect new resources to track. (dotnet)
- [x] QA
- [x] Update README.md 
- [x] Delete source code from altinn-studio repository
- [x] Delete outdated sonarcloud project

### Acceptance Criterias

- [x] Altinn.Platform.Models code is removed from the altinn-studio repository
- [x] Create a new branch in altinn-platform repo. Make a minor change. Create PR. Verify sonarcloud analysis is run. 
~~- [ ] From a fork of altinn-platform. Create a branch. Make a PR. Confirm that code coverage is available.~~
