### ISSUE TITLE
Add NAT Gateway to Events Function app

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#405]
Need to add support for NAT Gateway for Events function app. 
NAT Gateway will give the function app a single static IP for external communication.

Reuse Terraform code used by delegationevents function app.

## App owners that should be notified BEFORE the change
- [x] PAT

## Tasks
- [x] Push the change to all AT environments.
- [x] Identify which App owner we've communicated IP addresses to up til now. 
     - [x] Inform those parties directly
- [x] Write and Post a message about the change of IP address on slack. Make sure to clearly communicate that the change will occur in both TT02 and in production.

Deploy to TT and Prod is extracted into #448  #449 
## Additional information

The message shared on Slack 
```
Vi vil gjerne informere om en viktig endring som vil skje i Events den kommende tiden. Endringen beører utgående IP som benyttes for å pushe ut events til alle abonnenter. Vi endrer nå oppsettet vårt slik at det framover kun vil være én statisk IP å forholde seg til per miljø.
Ny IP for TT02: 20.100.24.41
Ny IP for produksjon: 20.100.46.139
Denne endringen gjør vi blant annet for å gjøre det enklere for både tjensteeiere og sluttbrukersystemer å vite at eventene som sendes kommer fra oss og ingen andre. Det vil da være mulig å whitelist IP-adressen som benyttes, og det garanteres at denne er statisk. Vi vil selvfølgelig informere dere i god tid hvis det blir behov for å endre IP-adressen ved en senere anledning.
Plan for utrulling av ny IP:
- TT02 kl 12:00 12. april
- Produksjon kl 12:00 19. april.
Hvis dere har spørsmål eller bekymringer, vennligst ikke nøl med å ta kontakt med oss. Takk for deres forståelse og samarbeid!
```
## Acceptance criteria
- [x] Static IP for all environments should be documented

**Comment by acn-sbuad** [comment]
Regression test successful in AT23

**Comment by acn-sbuad** [comment]
New IPs documented on Slack and in a Driftsmelding. Will be included in the new events documentation section as well.
