### ISSUE TITLE
Poc: Have Prometheus collect metrics and show in Grafana apps cluster

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#406]
### Description

The goal for this proof of concept is to prove that we can set up a Prometheus instance that can collect metrics. As a source of metrics we've decided to start with Traefik and Linkerd as we currently don't collect any data from those services.

Github dev say:  We don't support indentation quite yet. [issue](https://github.com/orgs/community/discussions/39106#discussioncomment-5556240)
So to fake it ident tasks have -

```[tasklist]
### In scope tasks
- [x] Set up a Prometheus service to gather data.
- [x] - Persistent storage
- [ ] - Adjust defaultRules: set rules not needed to false
- [x] Set up Grafana to display data
- [x] - Persistence
- [x] - Randomize admin password with autorotate
- [x] - Auth of user Grafana (AAD) @bengtfredh
- [x] Install necessary "agents?" in the app cluster for TTD in an AT/TT environment
- [x] Set up ingressroute traefik @bengtfredh
- [x] - After auth of users
- [x] Scrape metrics from kubernetes
- [x] Scrape metrics collection from Traefik
- [ ] https://github.com/Altinn/altinn-platform/issues/467
- [x] ~~Scrape metrics collection from pdf-generator~~
- [ ] ~~- https://github.com/browserless/chrome/issues/2810~~
- [ ] ~~- https://github.com/dewey/prometheus-browserless-exporter~~
- [ ] ~~- https://golangexample.com/a-prometheus-exporter-for-a-browserless-instance/~~
- [ ] https://github.com/Altinn/altinn-platform/issues/453
- [x] How to dynamically add scrape config
- [x] - https://stackoverflow.com/questions/63991541/dynamically-update-prometheus-scrape-config-based-on-pod-labels
- [x] Invite service owners to take part of POC
- [ ] - SKD
- [ ] - UDIR
- [ ] - BRG
- [ ] - KRT
- [ ] - SSB
- [ ] Look at turning down metrics collected by Azure
- [x] Deploy av dashboards, vi kan høre med FDK. Definisjoner i github.
- [ ] https://github.com/Altinn/altinn-platform/issues/468
- [x] Sette opp tilganger for brukere fra applikasjonseier
- [x] - Alle dashboards
- [x] - Developer - Editor tilgang
- [x] - Operations - Kun les
```

```[tasklist]
### Out of scope tasks
- [ ] Investigate alerts from prom/grafana
- [ ] - https://docs.robusta.dev/master/
- [x] Iac
- [ ] One central Prometheus instance can be added later.
```

### Analysis

```[tasklist]
### Tasks
- [x] Use helm chart [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack)
- [x] Deploy with branch [kube-prometheus-stack](https://dev.azure.com/brreg/altinn-apps-ops/_git/terraform-modules/branchCompare?baseVersion=GBmaster&targetVersion=GBkube-prometheus-stack)
- [x] Create scrape collection from pdf-generator
- [x] Create grafana dashboard for pdf-generator
- [x] - Count pdf created
- [x] - Count pdf in queue
- [x] - CPU count
- [x] - Memory count
```

```[tasklist]
### Conclusions
- [x] Use helm chart [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack)
- [ ] Use Grafana and prometheus for alerting
```

_No response_
```[tasklist]
### From Workshop
- [ ] Metrics from apps
- [ ] - https://github.com/prometheus-net/prometheus-net
- [ ] Alert about breaking changes
```

**Comment by bengtfredh** [comment]
POC is finished. Metrics in Grafana is deployed for all serviceowners.
