### ISSUE TITLE
Add filter for tag name on trigger for pipeline "PDF-generator master"

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#414]
### Description

Pipeline for "PDF-generator master" have trigger on branch gh-pages. This will trigger pipeline on updates on any chart in altinn-studio-charts.

Trigger should filter on tag "pdf-generator*" so it only trigger when pdf-generator chart is updated.

### Additional Information

[https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#:~:text=In%20addition%2[…]%20following%20format%3A](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#:~:text=In%20addition%20to%20specifying%20branch%20names%20in%20the%20branches%20lists%2C%20you%20can%20also%20configure%20triggers%20based%20on%20tags%20by%20using%20the%20following%20format%3A)

### Tasks

- [ ] Add filter for tag "pdf-generator*" on trigger for pipeline  "PDF-generator master"

### Acceptance Criterias

- [ ] Trigger start pipeline when pdf-genrator have new release
- [ ] Trigger do not care about other chart get updated

**Comment by annerisbakk** [comment]
Lukker saken, ref https://altinn.slack.com/archives/C02EVE4RU82/p1748329626402079
