### ISSUE TITLE
Remove docker_bridge_cidr from terraform azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#433]
### Description

docker_bridge_cidr is no longer supported by the API and deprecated in azurerm provider v3.49.0

### Tasks

- [x] remove dcoker_bridge_cidr from iac

### Acceptance Criterias

- [x] docker_bridge_cidr removed
- [x] pipeline run successful
