### ISSUE TITLE
Epic: Observability and monitoring  A3

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#439]
This issue is used to collect all issues related to observability and monitoring in A3.  

### Target groups:  
Pri 1:  
- Service owner operators
- Service owner developers  

Pri 2:     
- A3 operators
- A3 developers  

Pri 3:    
- A3 support
- A3 on-call engineer   

### List of issues:
```[tasklist]
## Issues
- [ ] https://github.com/Altinn/altinn-platform/issues/407
- [ ] https://github.com/Altinn/altinn-platform/issues/406
- [ ] https://github.com/Altinn/altinn-platform/issues/403
- [ ] https://github.com/Altinn/altinn-platform/issues/402
- [ ] https://github.com/Altinn/altinn-platform/issues/385
- [ ] https://github.com/Altinn/altinn-platform/issues/322
- [ ] https://github.com/Altinn/altinn-platform/issues/271
- [ ] https://github.com/Altinn/altinn-platform/issues/181
- [ ] https://github.com/Altinn/altinn-platform/issues/104
- [ ] https://github.com/Altinn/altinn-platform/issues/99
- [ ] https://github.com/Altinn/altinn-platform/issues/332
- [ ] https://github.com/Altinn/altinn-events/issues/507
- [ ] https://github.com/Altinn/altinn-platform/issues/361
- [ ] https://github.com/Altinn/altinn-platform/issues/507
```

### Features:
Metrics:
- Node CPU utilization
- Node Memory utilization
- Number of nodes
- Number of deployments
- List of deployments
- Number of pods
- Metrics CPU/Memory pods

Alerts:
- Custom alerts created by SO

### Tooling:
- Azure portal monitoring etc.
- Prometheus/Grafana

**Comment by tjololo** [comment]
All sub issues either closed or tracked other places
