### ISSUE TITLE
Deploy Events Function app NAT Gateway to TT02

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#448]
Need to add support for NAT Gateway for Events function app.
NAT Gateway will give the function app a single static IP for external communication.

## Tasks
- [x] 12.04.2023 12:00, perform the change in TT02
- [x] Investigate poison queue for events we're unable to send
- [x]  Follow up support questions from App owners related to missing events
- [x] Plan the rollout in production based on the findings from TT02
