### ISSUE TITLE
Deploy Events Function app NAT Gateway to PROD

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#449]
Need to add support for NAT Gateway for Events function app.
NAT Gateway will give the function app a single static IP for external communication.

## Tasks
- [ ] 19.04.2023 12:00, perform the change in PROD
- [ ] Investigate poison queue for events we're unable to send
- [ ]  Follow up support questions from App owners related to missing events

**Comment by SandGrainOne** [comment]
- Queues are empty
