### ISSUE TITLE
Update platform components to use CNAME for accessing CosmosDB and PostgreSQL

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#464]
### Description

All PostgreSQL server now have a CNAME that applications should use to access the server. 

CNAME records have been added in case of disaster recovery and other activities where a new server would need to be established under a new hostname. The CNAME record works as a form of alias to make it possible to switch between servers behind the scene without the need to update the application configuration.

### Additional Information

The list of CNAME records: 
- https://pedia.altinn.cloud/altinn-3/ops/backup-recovery/platform/postgresql/#dns
- https://github.com/Altinn/altinn-platform/issues/457

- AT21: at21-authorization-postgre.altinn.cloud
- AT21: at21-events-postgre.altinn.cloud
- AT21: at21-notifications-postgre.altinn.cloud
- AT21: at21-cosmosdb.altinn.cloud
- AT22: at22-authorization-postgre.altinn.cloud
- AT22: at22-events-postgre.altinn.cloud
- AT22: at22-notifications-postgre.altinn.cloud
- At22: at22-cosmosdb.altinn.cloud
- AT23: at23-authorization-postgre.altinn.cloud
- AT23: at23-events-postgre.altinn.cloud
- AT23: at23-notifications-postgre.altinn.cloud
- AT23: at23-cosmosdb.altinn.cloud
- AT24: at24-authorization-postgre.altinn.cloud
- AT24: at24-events-postgre.altinn.cloud
- AT24: at24-notifications-postgre.altinn.cloud
- AT24: at24-cosmosdb.altinn.cloud
- YT01: yt01-authorization-postgre.altinn.cloud
- YT01: yt01-events-postgre.altinn.cloud
- YT01: yt01-notifications-postgre.altinn.cloud
- YT01: yt01-cosmosdb.altinn.cloud
- TT02: tt02-authorization-postgre.altinn.no
- TT02: tt02-events-postgre.altinn.no
- TT02: tt02-notifications-postgre.altinn.no
- TT02: att02-cosmosdb.altinn.cloud
- PROD: authorization-postgre.altinn.no
- PROD: events-postgre.altinn.no
- PROD: notifications-postgre.altinn.no
- PROD: cosmosdb.altinn.no

### Tasks

- [x] Update postgre events
- [x] Update postgre authorization
- [x] Update postgre notifications
- [x] updaste postgre storage

**Comment by SandGrainOne** [comment]
Planning 25.09. We removed CNAME for CosmosDB.

**Comment by SandGrainOne** [comment]
Changes in Authorization handled in separate issue:
https://github.com/Altinn/altinn-authorization/issues/430
