### ISSUE TITLE
Teste deploy kube-prometheus-stack

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#468]
```[tasklist]
### Tasks
- [x] Change storage class from disk to folder for Grafana
- [x] - Added new StorageClass for grafana and prometheus with Terraform
- [ ] ~~Redundant Prometheus prevent hole on metrics timeline~~
- [ ] ~~- https://www.metricfire.com/blog/ha-kubernetes-monitoring-using-prometheus-and-thanos/~~
- [ ] ~~Update organization name on deploy to ${org}-${env} - today default is "Main Org."~~
- [ ] ~~- Not supported today (grafana issue 2908)~~
- [ ] ~~Backup?~~
```
