### ISSUE TITLE
Epic: Stability

### ISSUE THREAD

**Issue by aas-tbuar** [Altinn/altinn-platform#470]
### Description

This epic is used to collect issues related to Stability

### List of epics/issues

```[tasklist]
### Redundancy
- [ ] Add a draft title or issue reference here
- [ ] https://github.com/Altinn/altinn-platform/issues/441
```

```[tasklist]
### Performance
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Deploy
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Availability
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Backup and disaster recovery
- [ ] https://github.com/Altinn/altinn-platform/issues/441
```

```[tasklist]
### Observability and monitoring in A3
- [ ] https://github.com/Altinn/altinn-platform/issues/439
```

```[tasklist]
### Storage
- [ ] https://github.com/Altinn/altinn-storage/issues/193
```

**Comment by annerisbakk** [comment]
Lukket etter tilbakemelding fra Torkel - duplikat
