### ISSUE TITLE
Exclude leases lost exception in Azure Function from alert rule 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#472]
### Description

Currently, we get an alert in Slack whenever a lease is lost by a function. 
As there is no action point on our end in these cases we do not need to be alerted each time this happens. 
We should however ensure that an abnormal rise in exceptions, including leases lost exceptions, results in an alert in the proper channels.

### Tasks

- [ ] Adjust existing alert rule for functions
- [ ] Add if nessecary an alert rule for abnormal rise in errors for functions m
- [ ] QA
- [ ] Manual test

### Acceptance Criterias
- [ ] A single occurence of leases lost is not alerted to slack.

**Comment by SandGrainOne** [comment]
No longer using CosmosDB. The functions have been discontinuted
