### ISSUE TITLE
Network infrastructure for accessmanagementUI

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#476]
In the current solution, the access management key vault is set up with "Allow public access from all networks". The AM environments should be set up with a separate virtual network and dedicated subnet for the AMUI container app, so thatconnections to the key vault can be specified to increase security.

### Tasks

- [ ] Add AM vnet and subnet for AMUI container app in the Terraform code
- [ ] Deployed to AT21-24
- [ ] Deployed to YT01
- [ ] Deployed to TT02
- [ ] Deployed to PROD
- [ ] Test functionality
