### ISSUE TITLE
epic: traefik improvements and migrate to v3.x

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#527]
### Description

Epic to collect issues related to traefik improvements and migrate to v3.x

### In scope

* improvements in configuration
* performance testing and configuration
* steps to migrate to v3.x

### Out of scope

* chores

### Additional Information

* traefik last minor after releasing a new major will be supported for 1 year following the major release
* https://doc.traefik.io/traefik/v3.0/migration/v2-to-v3/
* https://doc.traefik.io/traefik/v2.10/migration/v2/#kubernetes-crds

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-studio-charts/issues/25
- [ ] https://github.com/Altinn/altinn-platform/issues/450
- [ ] https://github.com/Altinn/altinn-platform/issues/319
- [ ] https://github.com/Altinn/altinn-studio-charts/issues/30
- [ ] https://github.com/Altinn/altinn-studio-charts/issues/31
- [ ] https://github.com/Altinn/altinn-platform/issues/960
- [x] Patch running deployments to updated traefik api
```

**Comment by bengtfredh** [comment]
All but 1 issue closes - no need for epic to track 1 issue.
