### ISSUE TITLE
Move function apps to zone redundant service plan

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#529]
## Description

altinn-env-databackup-func   ->    altinn-env-databackup-fa
altinn-env-datacleanup-func  ->    altinn-env-datacleanup-fa
altinn-env-delegation-func    ->    altinn-env-delegation-fa
altinn-env-events-func           ->    altinn-env-events-fa
altinn-env-filescan-func         ->    altinn-env-filescan-fa

Old function apps are located in the resource group **altinnplatform-env-rg**. The new function apps are located in the resource group **altinnplatform-env-function-rg**.

Old and new function app should not be active at the same time.

## Operation plan

Outside of working hours: events and filescan 

During working hours: storage functions

Alerts are not affected. To move function apps, Disable existing functions, change release pipeline to go towards new function app and deploy.

## Tasks
Move function apps for the  following components in the listed environments:

```[tasklist]
### Storage - Data Cleanup
- [x] Update func url and key in [pipeline for load testing cleanup](https://dev.azure.com/brreg/altinn-studio/_build?definitionId=143&_a=summary)
- [x] AT21
- [x] AT22
- [x] AT23
- [x] AT24
- [x] YT01
- [x] TT02
- [x] Verify ok run in tt02
- [x] PROD
- [x] verify ok run in prod
```

```[tasklist]
### Storage - Data Backup
- [x] AT21
- [x] AT22
- [x] AT23
- [x] AT24
- [x] YT01
- [x] TT02
- [x] PROD
```

```[tasklist]
### Events
- [x] AT21
- [x] AT22
- [x] AT23
- [x] AT24
- [x] YT01
- [x] TT02
- [x] PROD
```

```[tasklist]
### Filescan
- [x] AT21
- [x] AT22
- [x] AT23
- [x] AT24
- [x] YT01
- [x] TT02
- [x] PROD
```

**Comment by acn-sbuad** [comment]
Issues with access to cosmos db from new function app
