### ISSUE TITLE
Add pg_dump backup for PostgreSQL for Storage

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#540]
```[tasklist]
### Tasks
- [x] Update PostgreSQL pg_dump backup for Storage AT21
- [x] Update PostgreSQL pg_dump backup for StorageAT22
- [x] Update PostgreSQL pg_dump backup for Storage AT23
- [x] Update PostgreSQL pg_dump backup for Storage AT24
- [x] Update PostgreSQL pg_dump backup for Storage YT01
- [x] Update PostgreSQL pg_dump backup for Storage TT02
- [x] Update PostgreSQL pg_dump backup for Storage PROD
```

Pipelines are located here:
https://dev.azure.com/brreg/altinn-studio-ops/_build?definitionScope=%5CBackup%20PostgreSQL
