### ISSUE TITLE
3.0 Backup/Recovery - Lag rutine og gjennomføre test

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-platform#55]
Det er et grunnleggende nødvendighet for 3.0 å ha på plass rutiner for backup og disaster recovery.
Disse skal testes og godkjennes.

https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049073/Matrise+for+Backup+og+Restore

## Tasks

- [x] #77
- [ ] #78
- [x] #79
- [ ] #80
- [ ] #81
- [x] Design/arkitektur for coldstorage/senitel
- [x] Sjekke opp backup for Senitel
- [x] Opprette figur som viser struktur og tjenester i Azure
- [x] Definer backuprutine av innhold i DNS (global) Fjordane IT
- [x] Lastbalanserer - Grensesnitt mellom Infra og 3.0

**Comment by ootneim** [comment]
Denne Epicen er erstattet av epicen https://github.com/Altinn/altinn-platform/issues/441
