### ISSUE TITLE
Upgrade Linkerd in platform

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#561]
### Description

Evaluate which Linkerd version to go for. Update all environments.

```[tasklist]
### Tasks
- [x] Upgrade platform in at21
- [x] Upgrade platform in at22
- [x] Upgrade platform in at23
- [x] Upgrade platform in at24
- [x] Upgrade platform in yt01
- [x] Upgrade platform in tt02
- [x] Upgrade platform in prod
```

### Threat modeling
This issue is not introducing any new moving parts. It's upgrading a software component.
