### ISSUE TITLE
Update DB handbook

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#587]
## Description
Update the [PostgreSQL best practices section](https://docs.altinn.studio/community/contributing/handbook/postgres/best-practice-postgresql/) in the developer handbook.

```[tasklist]
### Tasks
- [x] Write down how to define Enum types and a short description of why
- [x] Write something about why we prefer JsonB for Json documents
- [x] Write down a recommended procedure for analysing queries and deciding on an index
```

## Threat modeling
This is a documentation issue. No code changes.
