### ISSUE TITLE
Epic: Monitoring and observability Part 2

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#596]
### Description

Additional work on monitoring and observability. This issue is a follow up on the activities in issue #ob

### In scope

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/332
- [ ] https://github.com/Altinn/altinn-platform/issues/322
- [ ] https://github.com/Altinn/altinn-platform/issues/344
- [ ] https://github.com/Altinn/altinn-platform/issues/626
- [ ] https://github.com/Altinn/altinn-platform/issues/663
- [ ] Look in to overlaps between app insight and prometheus and how to handle it
- [ ] Centralize prometheus collections for display metrics cross clusters
- [ ] Create dashboard where you can see load in platform in sync with app clust
- [ ] Look in to collect prometheus metrics from Azure services i.e. postgresql, storageaccount
- [ ] Create public dashboard with key metrics
- [ ] https://github.com/Altinn/altinn-platform/issues/662
- [ ] Create dashboard for usecase testing for display availability
- [ ] Get status from altinn on digdir status page
- [ ] Send K6 status report to prometheus
- [ ] Get report on when platform components is deployed in cluster
- [ ] https://github.com/Altinn/altinn-platform/issues/661
```

### Tasks

```[tasklist]
### Tasks
```
