### ISSUE TITLE
Improve github bruksmønster pipelines to be more stable, prevent false notifications

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#599]
### Description

github bruksmønster pipeline use docker-compose and pull image from docker.io registry. docker.io registry have not been stable, and the tests fail because image is not available to pull.

### Additional Information

There is several ways to improve this:

1. Set up a pull-through cache to mitigate docker.io downtimes
2. Change to use https://github.com/marketplace/actions/k6-load-test
  2.1 Reason for use of docker-compose was to run same test locally. You can run github actions locally with https://github.com/nektos/act
3. Have some kind of error handling in pipeline in case image not avaiable.

### Tasks

- [ ] evaluate options to improve pipeline
- [ ] change pipelines to adapt new procedure

### Acceptance Criterias

- [ ] Pipeline run without notification if docker.io become unavailable
