### ISSUE TITLE
Epic: Restore platform version 1.0

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#603]
Restore procedures are located here: https://pedia.altinn.cloud/altinn-3/ops/backup-recovery/platform/

### Plowing through restore for the platform to test if data can be restored without complete data verification.

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/589
- [ ] https://github.com/Altinn/altinn-platform/issues/593
- [ ] https://github.com/Altinn/altinn-platform/issues/592
- [ ] https://github.com/Altinn/altinn-platform/issues/594
- [ ] https://github.com/Altinn/altinn-platform/issues/595
```

### Restore data with complete data verification

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/483
- [ ] https://github.com/Altinn/altinn-platform/issues/480
- [ ] https://github.com/Altinn/altinn-platform/issues/482
- [ ] https://github.com/Altinn/altinn-platform/issues/514
```
