### ISSUE TITLE
Upgrade platform AKS cluster size in AT

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#619]
## Description
We have started to experience issues in the AT environments due to high memory usage in the AKS clusters.
Platform clusters in the AT environments should be upgraded to a higher VM size to resolve the issues.
- Upgrade AT clusters from **Standard_B2ms** to **Standard_A2m_v2**
- Upgrade AKS version from 1.25.11 to 1.25.15

## Tasks
- [ ] Upgrade platform cluster in AT21
- [ ] Upgrade platform cluster in AT22
- [ ] Upgrade platform cluster in AT23
- [ ] Upgrade platform cluster in AT24
