### ISSUE TITLE
Reconstructing IAC and Azure structure for Authorization

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#622]
Reason:
Altinn-Authorization component should be written out and installed seperatly from the Altinn-platform component.
This will make both changes, security and upgrades less challenging.

Pre-refinement suggestions:

```
 - Create their own pipelines
          - Should GitHub be considered)
          - ,
 - Make IAC independent from the Platform IAC
          - Choice of code language
          - Could IAC be parten more than one Script
```

```
Move out all Authorization infrastructure to new subscriptions:
- Storage
- Auditlog
- PostgreDB(er)
- Accessmanagement 
- Kubernetes cluster (Running in the platform AKS now, so their own will increase cost)
             - Benytte anledningen til utføre en overgang til Container Apps
- Authentication Frontend
- FunctionApps
- AppInsights
- Keyvault(s)
```
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/635
- [ ] https://github.com/Altinn/altinn-platform/issues/637
- [ ] https://github.com/Altinn/altinn-platform/issues/650
- [ ] https://github.com/Altinn/altinn-platform/issues/642
- [ ] https://github.com/Altinn/altinn-platform/issues/638
- [ ] https://github.com/Altinn/altinn-platform/issues/644
- [ ] https://github.com/Altinn/altinn-platform/issues/646
- [ ] https://github.com/Altinn/altinn-platform/issues/645
- [ ] https://github.com/Altinn/altinn-platform/issues/643
- [ ] https://github.com/Altinn/altinn-platform/issues/640
- [ ] https://github.com/Altinn/altinn-platform/issues/641
- [ ] https://github.com/Altinn/altinn-platform/issues/639
```

**Comment by jonkjetiloye** [comment]
@SandGrainOne Her trenger vi vel ett oppstartsmøte hvor vi får diskutert hva vi ønsker å oppnå og hvordan i god tid før arbeidet starter og potensielt at autorisasjonsteamene sine egne ressurser kan bistå i nytt oppsett.

**Comment by annerisbakk** [comment]
@Herskis

**Comment by SandGrainOne** [comment]
@Herskis I see that this is not included in your teams board.

**Comment by Herskis** [comment]
@andreasisnes Denne Epic´en med underliggende saker, er den egentlig aktuell lenger?

**Comment by Herskis** [comment]
This issue was made to focus on a "lift and shift" solution for Authentication/Authorization from Altinn-platform-xxx subscriptions to their own subscription. The decision was made to not follow up on this solution since auth teams now either way are rewriting their solution, and in that progress they will also move to new subscriptions. When that issue is created, there will be a link to it in this Epic

**Comment by Herskis** [comment]
Here is the description of the new Auth architecture and their Epic https://github.com/Altinn/altinn-authorization-tmp/issues/3
