### ISSUE TITLE
Investigate AM-alerts not firing

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#623]
The AMUI alert is looking for too specific errors, needs to be updated and deployed to each environment

## Tasks
- [x] Update Terraform Script
- [x] Test new alert
- [x] Alert fix deployed to AT21
- [x] Alert fix deployed to AT22
- [x] Alert fix deployed to AT23
- [x] Alert fix deployed to AT24
- [x] Alert fix deployed to YT01
- [x] Alert fix deployed to TT02
- [x] Alert fix deployed to PROD
