### ISSUE TITLE
Upgrade PostgreSQL to version 16

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#634]
TT02: onsdag 18.9 kl 20:00-20:30 - endres til 25.9
Produksjon: onsdag 25.9 kl 20:00-20:30 - endres til 2. oktober

### Description

Version 16 of PostgreSQL has now been released and we should consider upgrading our servers.

https://www.postgresql.org/about/news/postgresql-16-released-2715/
https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-major-version-upgrade

### Additional Information
Databases: 
- storage
- events 
- notifications
- authorization
- authentication
- ~~auditlog~~ (do not support inplace upgrade)

### Tasks

- Make sure the PostgreSQL Flexible server is running HW "Burstable, B2s, 2 vCores, 4 GiB RAM, 64 GiB storage" or higher
- For TT02 and PROD environment. Create a duplicate PostgreSQL by using the "Restore" server option in the portal. If something is wrong after the upgrade.
- Trigger the upgrade progress by selecting "Upgrade" in the portal.
- Change the postgresql version in the pipeline from "15" to "16"
- Delete the duplicate PostgreSQL server (for TT02 and PROD)

### Acceptance Criterias

- Test database after upgrading.

### Deployment

- [x] AT21
   - [x] altinn-storage-db-at21-pgflex
   - [x] altinn-events-db-at21-pgflex
   - [x] altinn-notifications-db-at21-pgflex
   - [x] altinn-authorization-db-at21-pgflex
   - [x] altinn-authentication-db-at21-pgflex
- [x] AT22
   - [x] altinn-storage-db-at22-pgflex
   - [x] altinn-events-db-at22-pgflex
   - [x] altinn-notifications-db-at22-pgflex
   - [x] altinn-authorization-db-at22-pgflex
   - [x] altinn-authentication-db-at22-pgflex
- [x] AT23
   - [x] altinn-storage-db-at23-pgflex
   - [x] altinn-events-db-at23-pgflex
   - [x] altinn-notifications-db-at23-pgflex
   - [x] altinn-authorization-db-at23-pgflex
   - [x] altinn-authentication-db-at23-pgflex
 - [x] AT24
   - [x] altinn-storage-db-at24-pgflex
   - [x] altinn-events-db-at24-pgflex
   - [x] altinn-notifications-db-at24-pgflex
   - [x] altinn-authorization-db-at24-pgflex
   - [x] altinn-authentication-db-at24-pgflex
 - [x] YT01
   - [x] altinn-storage-db-yt01-pgflex
   - [x] altinn-events-db-yt01-pgflex
   - [x] altinn-notifications-db-yt01-pgflex
   - [x] altinn-authorization-db-yt01-pgflex
   - [x] altinn-authentication-db-yt01-pgflex
- [x] TT02
   - [x] altinn-storage-db-tt02-pgflex
   - [x] altinn-events-db-tt02-pgflex
   - [x] altinn-notifications-db-tt02-pgflex
   - [x] altinn-authorization-db-tt02-pgflex
   - [x] altinn-authentication-db-tt02-pgflex
- [x] PROD
   - [x] altinn-storage-db-prod-pgflex
   - [x] altinn-events-db-prod-pgflex
   - [x] altinn-notifications-db-prod-pgflex
   - [x] altinn-authorization-db-prod-pgflex
   - [x] altinn-authentication-db-prod-pgflex
