### ISSUE TITLE
Create new Azure Subscriptions for Authorization

### ISSUE THREAD

**Issue by Herskis** [Altinn/altinn-platform#635]
Create new Azure Subscriptions for Authorization

```[tasklist]
### Tasks
- [x] Altinn-Auth-Prod
- [x] Altinn-Auth-Staging
- [x] Altinn-Auth-Test
- [x] RBAC setup for new Subs
```
