### ISSUE TITLE
Change node pool size from A to B in AT environments

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#651]
## Description

- Change AKS node pool "nodepool1" from  **Standard_A2m_v2** to **Standard_B4ms** 
- Change AKS node pool "Filescan" from  **Standard_A2m_v2** to **Standard_B2ms** 

## Tasks
- [x] Change platform cluster in AT21
- [x] Change platform cluster in AT22
- [x] Change platform cluster in AT23
- [x] Change platform cluster in AT24
