### ISSUE TITLE
Upgrade AKS version platform

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#665]
AKS version 1.25.x support ended 14 jan, platform and eformidling clusters need to be upgraded to a supported version.

```[tasklist]
### Tasks
- [ ] Figure out which AKS version to upgrade to
- [ ] Change pipeline / terraform script
- [ ] Deployed to AT21-24
- [ ] Deployed to YT01
- [ ] Deployed to TT02
- [ ] Deployed to PROD
```
