### ISSUE TITLE
Automate generation and release of nuget for Altinn.Platform.Models

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-platform#666]
### Description

Currently, the generation of nuget packages for Altinn.Platform.Models is manual. 
This should be automated through workflows instead. 

Dev handbook on process: https://docs.altinn.studio/community/contributing/handbook/back-end/nuget-package/
### Additional Information

A lot of what we need here has already been done in the https://github.com/Altinn/altinn-legacy-clients repository.

### Tasks

- [x] Add necessary secret for nuget.org API use
- [x] Add Directory.build files for the project
- [x] Add a workflow to perform the necessary actions
- [x] QA
- [x] Test
- [ ] Update developer handbook with any discrepancies /updates /latest best practices

### Acceptance Criterias

- [x] Release notes are populated automatically
- [x] Creating a new release for Altinn.Platform.Models automatically generates new packages and publish them
