### ISSUE TITLE
Automatisk deploy til YT kl. 01 hver natt.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-platform#67]
## Description
We want up to date code in YT to be available for nightly tests.  A schedule should be set up to deploy all new code nightly

## Acceptance criteria
- [x] Release for YT should run on a schedule man-fri at 1 am for platform compoentns and functions

## Tasks
- [x] Set up schedule for platform components
- [x] Set up schedule for functions
- [x] QA
- [x] Test/ Verification

**Comment by Braskbram** [comment]
> 

Hvis vi ikke antar at dårlig ytelse ikke er showstopper for TT02 deploy? Hvor raskt ønsker vi feedback til utviklerne? Arbeidsteori bør diskuteres i teamet-

**Comment by acn-sbuad** [comment]
Trigger set for all platform components and functions.

**Comment by acn-sbuad** [comment]
Created new releases for all components (not including functions) 11.04. Verify that deploy to YT is executed 12.04
