### ISSUE TITLE
Ytelsesverifikasjon av 3.0 instanser presentert i 2.0 meldingsboks. 

### ISSUE THREAD

**Issue by Braskbram** [Altinn/altinn-platform#71]
FA er bekymret for ytelsen til 3.0 api. I løpet av sprinten må vi kjøre test, analysere miljøet, og adressere funn.

Test kjørt 4/4 viser at 3.0 kun klarer å levere innhold/instanser til 7 meldingsbokser pr sek. Dette er er for lavt (krav 30/s). Monitorering viser at storage går i taket på CPU. Antall instanser i testdata kan påvirke resultatet, og antall som returneres må verifiseres og eventuelt justeres. Teamet må ta ett arbeidsmøte for å utlede videre aksjoner og tiltak i hensikt å forbedre resultatet. Her må også tidsbruk estimeres. 

## Outcome from tasks

- [ ] Outdated SDK for cosmos utilized. This should be replaced. altinn/altinn-storage#16
- [ ] Uneven load observed across the storage instances Altinn/altinn-storage#17
- [ ] Some of the users have a lot of instances, this will not be the case in production for the time being. Would like to see test results from a test set closer to reality. Altinn/altinn-platform#86
- [ ] Side car for monitoring of storage would be useful to see status quo Altinn/altinn-storage#18
- [ ] Create a more performant message box specific instance search Altinn/altinn-storage#20

**Comment by ootneim** [comment]
Performance AKS cluster during testing 04.04.22

![image.png](https://images.zenhubusercontent.com/5ccfee4b770ae03e8fe27595/aaa8895d-49d4-4307-b8ae-df88a143a968)

![image.png](https://images.zenhubusercontent.com/5ccfee4b770ae03e8fe27595/b6b4e1f6-2564-4ecb-9e52-a7772b9c0680)
