### ISSUE TITLE
epic: enable flux gitops for continuous deployment

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#721]
### Description

Enable flux extension in AKS cluster
https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2?tabs=azure-cli

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/136
- [ ] https://github.com/Altinn/altinn-platform/issues/282
- [ ] https://github.com/Altinn/altinn-platform/issues/328
- [ ] https://github.com/Altinn/altinn-platform/issues/753
```
