### ISSUE TITLE
chore: Migrate apps pipelines from task charleszipp.azure-pipelines-tasks-terraform

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#725]
### Description

charleszipp.azure-pipelines-tasks-terraform is no longer maintained. Move to use:
https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks

At same time we can migrate to federated service connection.

### Tasks

- [x] switch out task from charleszipp.azure-pipelines-tasks-terraform to ms-devlabs.custom-terraform-tasks
- [x] update parameters for task
  - [x] Move state file config out to pipeline?
- [x] migrate service connection to fedrated service connection

### Acceptance Criterias

Pipeline run with no changes after migration
