### ISSUE TITLE
Migrate platform pipelines from task charleszipp.azure-pipelines-tasks-terraform

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#726]
### Description
https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform is no longer being maintained, Terraform pipeline tasks should be switched to use a new extension:
https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks
or:
https://marketplace.visualstudio.com/items?itemName=JasonBJohnson.azure-pipelines-tasks-terraform

Look into migrating from service connections to federated service connections

### Tasks

- [x] Look into which Terraform extension to use
- [x] Switch out task from charleszipp.azure-pipelines-tasks-terraform
- [x] Migrate service connection to fedrated service connection
