### ISSUE TITLE
Altinn-audit Expiring Certificates and Credentials April

### ISSUE THREAD

**Issue by Herskis** [Altinn/altinn-platform#736]
https://altinndevops.slack.com/archives/C014H7WPSUB/p1711960296653619

https://altinndevops.slack.com/archives/C014H7WPSUB/p1711960296817109

```[tasklist]
### Tasks
- [x] Credential Altinn Audit(fa30a0b2-450b-4f72-8630-062ffff88478) is expiring at 11.04.2024!
- [x] Credential brreg-altinn-studio-ops-de41df22-8dd0-435b-98dd-6152cd371e92(a4c00102-e583-4a30-bf32-f4282c3f5d5f) is expiring at 22.04.2024!
- [x] Credential SPR-AzDevOps-AltSentinel(8c038ed8-076e-4ce8-8a43-addadd56eeb0) is expiring at 24.04.2024!
- [x] Certificate altinn-cert-keyvault: am-ui-altinn-no is expiring at 25.04.2024!
- [x] Certificate altinn-cert-keyvault: am-ui-tt02-altinn-no is expiring at 25.04.2024!
- [x] FYI, Team Platform: Certificate CN=platform.altinn.no @ platform.altinn.no is expiring at 25.04.2024!
- [x] FYI, Team Platform: Certificate CN=platform.altinn.no @ platform.altinn.no is expiring at 25.04.2024!
- [x] FYI, Team Core: Secret Action publish Storage.Interfaces is expiring at 01.05.2024!
- [x] Certificate altinn-cert-keyvault: am-ui-yt01-altinn-cloud is expiring at 09.05.2024!
```
