### ISSUE TITLE
Create Vaulted backup for Blob Storage

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#752]
This issue can start the, Vaulted Backup for Storage Accounts is GA and Terrraform have support for it.

### Tasks
- [x] Create backup vault in the backup subscription
- [x] configure backup for platform storage accounts
- [x] Test Backup
- [x] Test Restore
- [x] remove object replication from the platform storage accounts
- [x] Documentation

Terraform branch: **_storage_backup_vault_**

- [x] altinnat21storage01
- [x] altinnat21storage02
- [ ] ~~altinnat21storage03~~ (Premium)
- [x] altinnat21storage04
- [ ] ~~altinnat21storage05~~ (Premium)
- [x] altinnat21storage07

**Deploy to Environments**

- [x] AT21
- [x] AT22
- [x] AT23
- [x] AT24
- [x] YT01
- [x] TT02
- [x] PROD
