### ISSUE TITLE
Migrate Eformidling pipelines from task charleszipp.azure-pipelines-tasks-terraform

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#771]
### Description
Change the pipeline tasks in the Eformidling pipelines from charleszipp to Microsoft tasks
Migrating from service connections to federated service connections

### Tasks

- [x] Update pipeline code for TT02
- [x] Update pipeline code for PROD
- [x] Migrate service connection to fedrated service connection
