### ISSUE TITLE
Many pdf generation fail in pdf-generator

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#772]
### Description of the bug

- Scaling is not optimal
- No metrics or logs is saved

### Additional Information

Shared work with core and apps
```[tasklist]
### Tasks
- [x] Investigate what resource request is needed
- [x] Update helm chart with new values for resource requests
- [ ] ~~Add sidecar to helm chart for prometheus endpoint~~
- [ ] ~~Set up scraping of pdf-generator~~
- [ ] ~~Add Grafana dashboard for display metrics from pdf-generator~~
```

**Comment by bengtfredh** [comment]
The critical issue with pdf generating looks to be solved. With more optimal scaling, it works better.
We still want to get metrics from pdf-generator and optimal logs.

**Comment by bengtfredh** [comment]
pdf generator periodically report status to log analytic workspace - we can query status from LAW. Feels like a hacked solution for getting prometheus metrics is not the way now.
