### ISSUE TITLE
epic: Onboarding SOC

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#783]
### Description

We will outsource SOC to Orange. This epic will collect issues related to onboarding.

### In scope

* Prepare environment according to spec from Orange
* Adjust what log that will be consumed by sentinal

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/784
- [ ] https://github.com/Altinn/altinn-platform/issues/790
- [ ] https://github.com/Altinn/altinn-platform/issues/797
- [x] Avtale opplæring for vaktlaget/sikkerhet/altinn-platform
```

**Comment by Herskis** [comment]
https://portal.azure.com/#view/Microsoft_Azure_Security_Insights/MainMenuBlade/~/DataConnectors/id/%2Fsubscriptions%2Fe1913d2a-6b4d-43c3-ae79-5cebfeb3bdd5%2Fresourcegroups%2Faltinn-sentinel-prod%2Fproviders%2Fmicrosoft.securityinsightsarg%2Fsentinel%2Faltinn-sentinel-prod-law

**Comment by Herskis** [comment]
GoLive 8x17 løsning fra og med 15/7.

Etter sommerferien starter arbeidet med 24/7 løsningen
