### ISSUE TITLE
Separate operational, application, security logging and put logdata in service owner subscription

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#784]
We will separate operational logging from application logging. Operational logging will be placed in separate log analytics workspace dedicated to each service owner. This makes it easier for cost analysis and access management.

### More info
- Name on new resource group will be "monitor-\<org\>-\<env\>-rg"
- Name on operational log analytics ws will be "operational-\<org\>-\<env\>-law"
- Name on application log analytics ws will be "application-\<org\>-\<env\>-law"
- Name on monitoring workspace "metrics-\<org\>-\<env\>-amw"
- Name on manageed grafana "grafana-\<org\>-{test|prod}"

### Reference
- Limit ContainerInsight to | ContainerLog or ContainerLogV2, KubeEvents, KubePodInventory | Recommended if you have enabled managed Prometheus metrics ( https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-data-collection-dcr?tabs=portal#:~:text=Recommended%20if%20you%20have%20enabled%20managed%20Prometheus%20metrics )

```[tasklist]
### Tasks
- [x] Add new resource group in service owner subscription for resources that is accessible for service owner
- [x] Create new log analytics workspaces (application,operational) in service owner resource group
- [x] Set up permissions for serviceowner account on monitor resourcegroup or workspaces
- [x] Send operational logs to newly created log analytics workspace
- [x] Add azure monitoring workspace
- [x] Move service owner ai to new resource group to collect all monitoring in 1 rg
- [x] Configure application insight to store logs in new law
- [x] Create managed grafana for each subscription (most practical because of cost and permission on metrics data)
- [x] Set up permissions on managed grafana
- [x] -- Grafana Admin - platform team
- [x] -- Grafana Editor - developer teams, service owner
- [x] Rewrite existing podmonitors and servicemonitors
- [x] Add dashboards to managed grafana
- [x] Remove kube-prometheus-stack
- [x] Delete storage accounts used for kube-prometheus-stack
- [x] Redirect https://\<org\>.apps.\<env\>.altinn.cloud/monitor to Azure Manged Grafana ref: https://ttd.apps.at21.altinn.cloud/monitor
- [ ] https://github.com/Altinn/altinn-platform/issues/811
```

### Notes
- Data ingested into either classic or workspace-based Application Insights is retained for 90 days without any charge.
- Grafana cost is kr1.079 per hour (ca kr 780/mnd) + kr66.184 per active user/month - compared to about kr 600-700 with OSS

### Deployment
```[tasklist]
### Tasks
- [x] at_ring1
- [x] at_ring2
- [x] tt_ring1
- [x] tt_ring2
- [x] prod_ring1
- [x] prod_ring2
```

**Comment by bengtfredh** [comment]
Waiting to deploy prod to after @bengtfredh is back from vacation. It is not preferable to deploy something this big to production the day before vacation
