### ISSUE TITLE
Subdomene for Arbeidsflate

### ISSUE THREAD

**Issue by arealmaas** [Altinn/altinn-platform#787]
Vi er i prosessen med å få satt opp ordentlige domener for Arbeidsflate på et altinn-domene. 

Vi tenkte å sette opp arbeidsflate på:
- [af-test.altinn.no](http://af-test.altinn.no/)
- [af-staging.altinn.no](http://af-staging.altinn.no/)
- [af.altinn.no](http://af.altinn.no/)

Per nå er det bare testmiljøet, altså [af-test.altinn.no](http://af-test.altinn.no/) som trengs å konfigureres.

Der trenger vi et sertifikat (pfx) og en peker fra DNS til IP: 20.100.12.48
```[tasklist]
### Tasks
- [x] A-Record test
- [x] A-record-staging
- [x] a-record-prod
- [x] cert test
- [x] cert staging
- [x] cert prod
```

**Comment by bengtfredh** [comment]
Din sak 2405 3076: "Nye SSL certificates for Arbeidsflate/Dialogporten" er registrert

**Comment by arealmaas** [comment]
>Videre flytter vi Dialogporten til egen Management group i Azure , og oppretter i tillegg Dialogporten-Staging som egen subscription

Blir dette en del av denne tasken og hva er ca ETA på sertifikater for miljø? Vi har som mål å få satt opp Staging-miljø og certs for Test og Staging denne sprinten (2 uker) om det lar seg gjøre!

**Comment by bengtfredh** [comment]
@arealmaas 
I dont have an ETA on the cert. Normally we have them in a couple of day, I will follow up on Monday.

**Comment by bengtfredh** [comment]
@arealmaas
cert er levert og lastet opp i altinn-cert-keyvault.

**Comment by Herskis** [comment]
Prod/Staging tilgang for:
- [ ] Skogstad, Ole Jørgen Gisnås 
- [ ] Sandgren, Magnus
- [ ] Haug, Knut Espen
- [ ] Almaas, Are
- [ ] Langfors, Bjørn Dybvik

**Comment by arealmaas** [comment]
I tillegg skulle vi gjerne lagt til:

Bredland, Frank Lyder
Midteide, Alexander
Scully, Sean Erik

Det er de som jobber med arbeidsflate

**Comment by arealmaas** [comment]
The tasks related to A-records blocked by https://github.com/Altinn/altinn-platform/issues/821

**Comment by arealmaas** [comment]
IP for A-record til staging er: 51.13.56.193

**Comment by bengtfredh** [comment]
af.tt.altinn.no.	7200	IN	A	51.13.56.193

**Comment by arealmaas** [comment]
Da har vi fått IP for produksjon. 
51.13.51.134

Så: `af.altinn.no. 7200 IN A  51.13.51.134`
