### ISSUE TITLE
POC: Sette opp Sentinel i egen subscription

### ISSUE THREAD

**Issue by Herskis** [Altinn/altinn-platform#790]
```[tasklist]
### Tasks
- [x] Opprette subscription Altinn-Sentinel-Prod
- [x] Sette opp eget law og tilknytte ny sentinel
- [x] sette opp connectorer
- [x] Logging fra tjenesteeier subscription
- [x] AppRequests
- [x] AppDependencies
- [x] AppTraces
- [x] ApiManagementGatewayLogs
- [x] Perf
```

**Comment by ootneim** [comment]
@Herskis 
Tabellene:
- AppRequest
- AppDependencies
- AppTraces
- AppExeptions
- AppEvents
- AppPageViews
- AppAvailabilityResults

Kommer fra Applicatoion Inslight som lagrer data i dette workspace.


**Her er en spørring som viser hvor mye som er lagret i tabellene siste 30 dager:**
```
let pricePerGB_NOK = 28.7; // Prisen per GB i NOK
let totalIngestedGB = toscalar(
    Usage
    | where TimeGenerated > startofday(ago(30d))
    | where IsBillable == true
    | where DataType in ('AppRequests', 'AppDependencies', 'AppTraces', 'AppExceptions', 'AppEvents', 'AppMetrics', 'AppPageViews', 'AppAvailabilityResults')
    | summarize TotalIngestedGB = sum(Quantity) / 1000
);
Usage
| where TimeGenerated > startofday(ago(30d))
| where IsBillable == true
| where DataType in ('AppRequests', 'AppDependencies', 'AppTraces', 'AppExceptions', 'AppEvents', 'AppMetrics', 'AppPageViews', 'AppAvailabilityResults')
| summarize IngestedGB = sum(Quantity) / 1000 by DataType
| extend PricePerTable_NOK = round(IngestedGB * pricePerGB_NOK, 2)
| extend Percentage = IngestedGB * 100.0 / totalIngestedGB
| project DataType, IngestedGB = round(IngestedGB, 2), Percentage = round(Percentage, 2), PricePerTable_NOK
| union (
    Usage
    | where TimeGenerated > startofday(ago(30d))
    | where IsBillable == true
    | where DataType in ('AppRequests', 'AppDependencies', 'AppTraces', 'AppExceptions', 'AppEvents', 'AppMetrics', 'AppPageViews', 'AppAvailabilityResults')
    | summarize IngestedGB = sum(Quantity) / 1000
    | extend DataType = "Total"
    | extend Percentage = 100.0
    | project DataType, IngestedGB = round(IngestedGB, 2), Percentage, PricePerTable_NOK = round(IngestedGB * pricePerGB_NOK, 2)
)

``` 


![Image](https://github.com/Altinn/altinn-platform/assets/49302758/28e97458-628e-4abb-be38-7ee0ab440670)

**Comment by Herskis** [comment]
POC has been upgraded to solution
