### ISSUE TITLE
Remove High Availability for PostgreSQL TT02

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#796]
```[tasklist]
### Tasks
- [x] altinn-auditlog-db-tt02-pgflex
- [x] altinn-auditlog-db-yt01-pgflex
- [x] altinn-authentication-db-tt02-pgflex
- [x] altinn-authentication-db-yt01-pgflex
- [x] altinn-authorization-db-tt02-pgflex
- [x] altinn-authorization-db-tt02-pgflex
- [x] altinn-eformidling-db-tt02-pgflex
- [x] altinn-events-db-tt02-pgflex
- [x] altinn-events-db-yt01-pgflex
- [x] altinn-events-db-yt01-pgflex Justere vCpu og Ram tilsvarende produksjon
- [x] altinn-notifications-db-tt02-pgflex
- [x] altinn-notifications-db-yt01-pgflex
- [x] altinn-storage-db-tt02-pgflex
- [x] altinn-storage-db-yt01-pgflex
- [x] sfvt-dgm-tt02-psql
```

**Comment by ootneim** [comment]
@bengtfredh 

Da er det "sfvt-dgm-tt02-psql" som gjenstår å få disablet HA.

Her er en måte å løse på at det kun er tilgjengelig i prod

```
  dynamic "high_availability" {
        for_each = var.environment == "prod" ? [1] : []
        content {
            mode = "ZoneRedundant"
        }
    }

```
