### ISSUE TITLE
Backup vault policy for PostgreSQL Flexible is now available for Terraform

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#799]
Terraform configuration for enabeling backup vaut for PostgreSQL Flexible server is availabe from v3.107

azurerm_data_protection_backup_policy_postgresql_flexible_server

Only the Backup Policy is supported by Terraform at the moment. (backup is still in preview)

```[tasklist]
### Tasks
- [x] Create Backup policy using Terraform
- [x] Configure manually PostgreSQL Flexible backup using the portal
- [x] Verify the backup is done correctly.
- [x] Test to restore the backup.
```
Terraform code:

```

resource "azurerm_role_assignment" "postgresql_storage" {
  scope                = azurerm_postgresql_flexible_server.storage.id
  role_definition_name = "Contributor"
  principal_id         = azurerm_data_protection_backup_vault.platform.identity[0].principal_id
}

resource "azurerm_role_assignment" "resourcegroup" {
  scope                = data.azurerm_resource_group.rg.id
  role_definition_name = "Contributor"
  principal_id         = azurerm_data_protection_backup_vault.platform.identity[0].principal_id
}

resource "azurerm_role_assignment" "postgresql_storage_account" {
  scope                = azurerm_storage_account.sa.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_data_protection_backup_vault.platform.identity[0].principal_id
}

resource "azurerm_data_protection_backup_policy_postgresql_flexible_server" "storage" {
  name                            = "postgresql-storage-backup-policy"
  vault_id                        = azurerm_data_protection_backup_vault.platform.id
  backup_repeating_time_intervals = ["R/2021-05-23T02:30:00+00:00/P1D"]
  time_zone                       = "W. Europe Standard Time"

  default_retention_rule {
    life_cycle {
      duration        = "P6M"
      data_store_type = "VaultStore"
    }
  }

  retention_rule {
    name     = "weekly"
    #duration = "P6M"
    priority = 20

    criteria {
      absolute_criteria = "FirstOfWeek"
    }

    life_cycle {
      duration        = "P6M"
      data_store_type = "VaultStore"
    }
  }
  
  retention_rule {
    name     = "dayly"
    #duration = "P1D"
    priority = 15

    criteria {
      days_of_week           = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
      #scheduled_backup_times = ["2021-05-23T02:30:00Z"]
    }

    life_cycle {
      duration        = "P1M"
      data_store_type = "VaultStore"
    }
  }
  
}
``` 

Terraform koden ligger i branchen  **_postgresql-backup vault_**
