### ISSUE TITLE
Move APIM platform products to Terraform script

### ISSUE THREAD

**Issue by simon-ellefsen** [Altinn/altinn-platform#800]
Currently all APIM products are created with a seperate script not related to Terraform. To be able to automate creation of subscriptions we need to reference said products. Products should instead be created and maintained in the Platform Terraform script.

```[tasklist]
### Tasks
- [ ] Add already existing APIM products to tfstate (gateway)
- [ ] Add APIM products to Terraform code
- [ ] Make sure the old script for creating products is removed / altered to match these changes
```

**Comment by simon-ellefsen** [comment]
Yes I agree, this will just add more work and clutter than is needed for the other teams. Closing it.
