### ISSUE TITLE
Add Managed Identity in prod and staging Azure subscription to be used by github actions

### ISSUE THREAD

**Issue by arealmaas** [Altinn/altinn-platform#821]
### Description

In order to set up our staging and production environments, we need a Managed Identity that we can use in our github actions. All our Azure resources are created in Github Actions.

We want to use OIDC in order to authenticate the Managed Identity. https://github.com/azure/login/tree/v1/?tab=readme-ov-file#login-with-openid-connect-oidc-recommended

In order to do so we either need access to create user assigned managed identities in our subscriptions, or would need to have these set up by Platform. If we go for the latter, I added a detailed description of how to do this below. 

### Additional Information

**For production:**

1. [Create the user-assigned managed identity](https://learn.microsoft.com/en-gb/entra/identity/managed-identities-azure-resources/how-manage-user-assigned-managed-identities?pivots=identity-mi-methods-azp#create-a-user-assigned-managed-identity):  with the name: dialogporten-github-actions

2. [Configure a federated identity credential on a user-assigned managed identity](https://learn.microsoft.com/entra/workload-id/workload-identity-federation-create-trust-user-assigned-managed-identity?pivots=identity-wif-mi-methods-azp#github-actions-deploying-azure-resources) 

Name: Production
Entity type: Tag: `v*.*.*`

Provide us with the managed identity Client ID and Tenant ID.

**For staging:**

1. [Create the user-assigned managed identity](https://learn.microsoft.com/en-gb/entra/identity/managed-identities-azure-resources/how-manage-user-assigned-managed-identities?pivots=identity-mi-methods-azp#create-a-user-assigned-managed-identity):  with the name: dialogporten-github-actions

2. [Configure a federated identity credential on a user-assigned managed identity](https://learn.microsoft.com/entra/workload-id/workload-identity-federation-create-trust-user-assigned-managed-identity?pivots=identity-wif-mi-methods-azp#github-actions-deploying-azure-resources) 

Name: Staging
Entity type: Tag: `v*.*.*`
Entity type: Branch: `main`

Provide us with the managed identity Client ID and Tenant ID.

### Tasks

- [ ] Create the user-assigned managed identity for production
- [ ] Configure a federated identity credential on the identity for production
- [ ] Provide Dialogporten with Client ID and Tenant ID for production
- [ ] Create the user-assigned managed identity for staging
- [ ] Configure a federated identity credential on the identity for staging
- [ ] Provide Dialogporten with Client ID and Tenant ID for staging

### Acceptance Criterias

As the Dialogporten team, we would like to have access to or for the platform team to create a managed identity, so we can deploy resources in the new **staging** and **production** environments
