### ISSUE TITLE
Migrate altinn-receipt to new deployment strategy

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#826]
Altinn-receipt should be delployed wit the new CI/CD strategy

```[tasklist]
### Tasks
- [x] Update infrastructure code for platform
- [x] Propose changes for receipt's repo https://github.com/Altinn/altinn-receipt/pull/320
- [x] deploy to at23
- [x] deploy to at21
- [x] deploy to at22
- [x] deploy to at24
- [x] deploy to tt02
- [x] deploy to yt
- [x] deploy to prod
```
