### ISSUE TITLE
Epic: improve observability of Traefik

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#847]
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/848
- [ ] https://github.com/Altinn/altinn-platform/issues/850
- [ ] https://github.com/Altinn/altinn-platform/issues/855
- [ ] https://github.com/Altinn/altinn-platform/issues/873
```
