### ISSUE TITLE
Traefik: Create a  latency SLO 

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#848]
We might not need this if we feel that is enough with the availability SLO

```[tasklist]
### Tasks
- [x] deploy to ATxx
- [x] deploy to tt02
- [x] deploy yo prod
```
