### ISSUE TITLE
Epic: improve observability of Linkerd

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#851]
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/852
- [ ] https://github.com/Altinn/altinn-platform/issues/853
- [ ] https://github.com/Altinn/altinn-platform/issues/854
- [ ] https://github.com/Altinn/altinn-platform/issues/856
- [ ] https://github.com/Altinn/altinn-platform/issues/857
```
