### ISSUE TITLE
Linkerd: Create a latency SLO

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#852]
Probably better to investigate first which metrics are important first https://github.com/Altinn/altinn-platform/issues/853

```[tasklist]
### Tasks
- [ ] deploy to atxx
- [ ] deploy to tt02
- [ ] deploy to prod
```

**Comment by monteiro-renato** [comment]
It might be a bit tricky to get this one right at the moment.

[Latency of control plane components. These levels should be set empirically and unexpected changes should be investigated.](https://docs.buoyant.io/runbook/monitoring-linkerd/#monitoring-linkerd-control-plane-metrics.)

**Comment by monteiro-renato** [comment]
I've created a relaxed SLO for now. It should not trigger any alerts unless something seriously wrong happens.
We can tweak the configured values once we know what "normal" is.
