### ISSUE TITLE
Traefik: create an availability SLO

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#855]
Probably better to follow error codes on` traefik_service_requests_total`

```[tasklist]
### Tasks
- [x] deploy to atxx
- [x] deploy to tt02
- [x] deploy to prod
- [x] deploy to yt01
```

**Comment by sduranc** [comment]
Trying this:
```
  indicator:
    ratio:
      errors:
        metric: traefik_service_requests_total{code~"5..|499"}
      total:
        metric: traefik_service_requests_total
```
