### ISSUE TITLE
LInkerd: create an availability SLO

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#856]
Probably better to investigate first which metrics are important first https://github.com/Altinn/altinn-platform/issues/853

```[tasklist]
### Tasks
- [ ] deploy to atxx
- [ ] deploy to tt02
- [ ] deploy to prod
```

**Comment by monteiro-renato** [comment]
I've opened a PR based on:
[Success rate of control plane components. This should never drop below 100%; any failure responses are a sign that something is going wrong.](https://docs.buoyant.io/runbook/monitoring-linkerd/#monitoring-linkerd-control-plane-metrics)
