### ISSUE TITLE
Migrate altinn-access-management to the new CI/CD

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#864]
- Discuss with the team if we're lacking some features
- See what to do with their Helm chart and how to trigger the new release for the app from their repo etc
- 
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/902
- [ ] https://github.com/Altinn/altinn-platform/issues/903
- [ ] https://github.com/Altinn/altinn-platform/issues/904
```

**Comment by khanrn** [comment]
[andreasisnes](https://github.com/andreasisnes) suggested to move this to the Done columns! 🙂
