### ISSUE TITLE
New infrastructure in production for Digitalt dødsbo

### ISSUE THREAD

**Issue by erlendoksvoll** [Altinn/altinn-platform#870]
In order to prepare for go live of Digitalt dødsbo we need to create the relevant resources in production.

The following resources are used in test and corresponding resources for production are needed:

Altinn 3 apps: 
•	oed 
•	oed-declaration 
•	oed-events 

Keyvaults: 
•	digdir-tt02-apps-kv  
•	oed-kv 

Azure Funcs: 
•	oed-feedpoller 

Resource groups: 
•	altinn-digdir-oed-tt02-rg 

App service: 
•	oed-authz 

PostgreSQL db: 
•	oed-authz-pg 

We need to discuss the best way forward so we can provide our external partners with relevant IPs etc. :)

```[tasklist]
### Tasks
- [x] Clean up resources in altinn-digdir-oed-tt02-rg not in use (Erlend)
- [x] Create IaC for infra based on Altinn-DIGDIR-Test (Bengt)
- [x] Create resource group altinn-digdir-oed-prod-rg in Altinn-DIGDIR-Prod (Bengt)
- [x] Deploy resources in Altinn-DIGDIR-Prod with IaC (Bengt)
```
