### ISSUE TITLE
Epic: establish a centralized observability environment

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#907]
- Currently we have grafana per environment/(service)owner. This is not optimal when it comes to on-call or just having a good overview of all the environments. Therefore we need to gather observability signals in one place.
- The initial idea is to rely on managed solutions but we should evaluate the feasibility of this
- This epic will have as an outcome a proposed solution, along with an RFC and a PoC.

 
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/908
- [ ] https://github.com/Altinn/altinn-platform/issues/909
- [ ] https://github.com/Altinn/altinn-platform/issues/910
- [ ] https://github.com/Altinn/altinn-platform/issues/911
- [ ] https://github.com/Altinn/altinn-platform/issues/912
- [ ] https://github.com/Altinn/altinn-platform/issues/913
- [ ] https://github.com/Altinn/altinn-platform/issues/917
- [ ] https://github.com/Altinn/altinn-platform/issues/919
- [ ] https://github.com/Altinn/altinn-platform/issues/995
- [ ] https://github.com/Altinn/altinn-platform/issues/996
- [ ] https://github.com/Altinn/altinn-platform/issues/998
- [ ] https://github.com/Altinn/altinn-platform/issues/1000
- [ ] https://github.com/Altinn/altinn-platform/issues/1083
- [ ] https://github.com/Altinn/altinn-platform/issues/1084
- [ ] https://github.com/Altinn/altinn-platform/issues/1120
```
