### ISSUE TITLE
Create centralized grafana

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#908]
We will create a Azure hosted Grafana for reporting on centralized metrics.
```[tasklist]
### Tasks
- [x] Deploy a hosted grafana
- [x] Review and deploy permissions
- [x] Review what datasources is needed
```

### Summary
- grafana url:  https://altinn-grafana-test-b2b8dpdkcvfuhfd3.eno.grafana.azure.com 
- Permission to grafana for groups: altinn_30_operations, altinn_30_operations_prod
