### ISSUE TITLE
Define the agent that exports obs signals to the centralized obs env

### ISSUE THREAD

**Issue by sduranc** [Altinn/altinn-platform#911]
To export: metrics, logs, tracing, (profiling).
Requirements:
- Try to avoid secrets, preferably use workload identity (WI)
- If WI isn't available yet, at least make use of secrets through a vault (via WI)
- Whether we choose one or more agents, at least metrics, logs and traces should be exported

Acceptance criteria:
- [ ] Have an app exporting its signals to the centralized observability envinronment
 
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-platform/issues/936
- [ ] https://github.com/Altinn/altinn-platform/issues/935
- [ ] https://github.com/Altinn/altinn-platform/issues/937
- [ ] https://github.com/Altinn/altinn-platform/issues/938
```

**Comment by monteiro-renato** [comment]
TODO: Documentation.
Current solution only supports metrics and logs (Azure limitation).
