### ISSUE TITLE
chore: renew tls certs expire date 26.10.2024

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#922]
### Description

Create csr and order new certs.

```[tasklist]
### Tasks
- [x] platform-at2x-altinn-cloud
- [x] platform-tt02-altinn-no
- [x] star-apps-altinn-no
- [x] star-apps-tt02-altinn-no
- [x] star-altinn-cloud
- [x] star-altinn-no
- [x] altinn-no/www-altinn-no
```

**Comment by bengtfredh** [comment]
Order ticket 2409 3432

**Comment by bengtfredh** [comment]
@simon-ellefsen FYI - if you need to do something to update cert
