### ISSUE TITLE
epic: implement ipv6

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#941]
### Description

According to [Forskrift om IT-standarder i offentlig forvaltning](https://lovdata.no/dokument/SF/forskrift/2013-04-05-959) we need to implement ipv6

> § 12.Obligatoriske grunnleggende nettverksstandarder
> Offentlige virksomheter skal sette krav til støtte av både IPv4 og IPv6 i alt nytt nettverksutstyr og all IP-avhengig programvare som anskaffes.
> 
> Offentlige virksomheter skal gjøre alle nye og eksisterende, eksternt publiserte tjenester tilgjengelig både på IPv4 og IPv6, med unntak av peer to peer kommunikasjon mellom offentlige virksomheter, der man kan legge om på best egnet tidspunkt.
> 
> Alle interne klienter i offentlige virksomheter skal ha tilsvarende tilgang til eksterne tjenester publisert på IPv4 og IPv6.
> 
> Nye interne nett og løsninger i offentlige virksomheter skal ha støtte for IPv6. Det er tillatt å støtte IPv4 i tillegg.

This epic will track activities related to be compliant. We have commited to a deadline 01.01.2025 to provide dual stack on published services.

### In scope

* provide dual stack on published services
* High level architecture description how we want to implement ipv6.
I started on some doc: https://digdir.atlassian.net/wiki/x/DIBvpw
* This epic will focus on published services:
  - [ ] platform ingress/egress (apim)
  - [x] apps ingress/egress
  - [x] altinncdn
  - ~~[ ] keyvault~~
  - [ ] container app (auth)
  - [ ] altinn.studio
  - [x] docs.altinn.studio
  - [x] azuredevops (studio bygglogs)

### Out of scope

* internal services are not priority in this epic
* ATxx is out of scope but will get ipv6 where it is practical

### Additional Information
* apim ipv6 q1 2025
  * classic tier only permium
  * v2 tier standard, premium
*  aks
  * application gateway for containers?
  * load balancer?
  * app gateway for all clusters?

### Tasks

```[tasklist]
### Tasks
- [ ] #411
- [ ] Clarify activities with Altinn Studio (Espen)
- [ ] Check what to do with Keyvault (Bengt)
- [ ] Investigate how/what container apps (Simon)
- [ ] https://github.com/Altinn/altinn-platform/issues/971
- [ ] https://github.com/Altinn/altinn-platform/issues/1143
- [ ] https://github.com/Altinn/altinn-platform/issues/1046
```
