### ISSUE TITLE
Storage for data migrated from Altinn2

### ISSUE THREAD

**Issue by tjololo** [Altinn/altinn-platform#954]
### Description

Data from Altinn 2 needs to be moved into the Altinn 3 solution as historical data.
This data should not be stored alongside the new data produced in Altinn 3 but be stored separately.
Some service owners are not going to migrate to Altinn 3, but their data from Altinn 2 still needs to be moved.

### In scope

- [x] #955
- [x] #966
- [x] #1024
- [x] Separate release section for historic-data-only service owners
- [x] Support for moving service owners from historic to active category (creating the additional infrastructure)
- [x] Create subscriptions for all service owners
- [x] Provision historic-data-only infrastructure for all existing service owners
- [x] #1090

### Out of scope

The actual moving of the data and integrating it into the solution is not a part of our Epic and should be covered in issues owned and managed by other teams.
