### ISSUE TITLE
Azure Subscriptions for Serviceowners with A2 data

### ISSUE THREAD

**Issue by Herskis** [Altinn/altinn-platform#966]
Serviceowners with Altinn 2 data are in need of their own subscriptions

```[tasklist]
### Main tasks
- [x] Create missing subscriptions for serviceowners
- [x] All subs Prod
- [x] All subs Test only
- [x] Update list of subscriptions for MS Unified Support
```

```[tasklist]
### SO med prod og test subscription
- [x] FD | Fiskeridirektoratet | 971203420
- [x] NKR | Kulturdirektoratet | 971527412
- [x] BRG | Registerenheten i Brønnøysund | 974760673
- [x] DAT | Arbeidstilsynet | 974761211
- [x] MAT | Mattilsynet | 985399077
- [x] STAMI | Statens arbeidsmiljøinstitutt | 874761222
- [x] KYV | KYSTVERKET | 874783242
- [x] SVV | Statens vegvesen | 971032081
- [x] SSB | Statistisk sentralbyrå | 971526920
- [x] SPK | Statens Pensjonskasse | 974760967
- [x] DIBK | DIREKTORATET FOR BYGGKVALITET | 974760223
- [x] LT | Luftfartstilsynet | 981105516
- [x] VIGO | VIGO IKS | 998283914
- [x] TRA | Tilsynsrådet for advokatvirksomhet | 914459265
- [x] OK | Oslo kommune | 971183675
- [x] PAT | Patentstyret | 971526157
- [x] SFD | Sjøfartsdirektoratet | 974761262
- [x] SRF | Statens Sivilrettsforvaltning | 986186999
- [x] HDIR | Helsedirektoratet | 983544622
- [x] NPE | Norsk pasientskadeerstatning | 984936923
- [x] DIGDIR | Digitaliseringsdirektoratet | 991825827
- [x] KRT | Kredittilsynet | 840747972
- [x] DSB | Dir for samfunnssikkerhet og bereds | 974760983
- [x] BUF | Barne-, ungdoms- og familiedirektoratet | 986128433
- [x] VALG | Valgdirektoratet | 916132727
- [x] UDIR | Utdanningsdirektoratet | 970018131
- [x] SKD | Skatteetaten | 974761076
- [x] SLV | Direktoratet for medisinske produkter | 974761122
- [x] LTS | Lotteri- og stiftelsestilsynet | 982391490
- [x] HMRHF | Helse Møre og Romsdal HF | 997005562
- [x] TAD | Tolletaten | 880455702
- [x] NAV | NAV | 889640782
- [x] ASF | Samlesider | 974706121
- [x] BFT | Basefarm TEST | 982211743
- [x] ACN | Accenture Etat Altinn | 492037605
- [x] EHLS | Direktoratet for e-helse | 915933149 - AM-OK
- [x] SLK | Statens Lånekasse for utdanning | 960885406 - AM-OK
- [x] SLF | Landbruksdirektoratet | 981544315 - AM-OK
- [x] TTD | Testdepartement | 405003309
- [x] KT | Konkurransetilsynet | 974761246 - AM-OK
- [x] FK30 | Viken Fylkeskommune | 921693230 - AM-OK
- [x] FK | Fellesordn for avtalefestet pensjon | 987414502
- [x] DPA | Datatilsynet | 974761467
- [x] SHT | Statens havarikommisjon | 881143712
- [x] SI | Statens innkrevingssentral | 971648198
- [x] ENO | Enova SF | 983609155
- [x] K3030 | Lillestrøm kommune | 820710592
- [x] K0231 | Skedsmo kommune | 938275130
```

```[tasklist]
### SO med bare testsubscription
- [x] STFK | Sør-Trøndelag fylkeskommune | 910018469
- [x] K0220 | Asker kommune | 944382038
- [x] POD | Politiet | 910284096
- [x] ABC | Importert av ER | 980123456
- [x] KURS | Kursetaten| 910595083
- [x] NPT | Post- og teletilsynet | 910624016
- [x] KS | Kommuner/fylkeskommuner | 910171445
```
